// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qceffcmjupykcwktdfti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjZWZmY21qdXB5a2N3a3RkZnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDY4NDYsImV4cCI6MjA2NTUyMjg0Nn0.vkE56UbOPUUyJe0Iey5Tlykc9YQs8oR0aQIxmTrSEbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);